In [1]:
# setup and load Data

from google.colab import drive
import numpy as np
import pandas as pd
import os
from datetime import datetime

drive.mount('/content/drive')

project_path='/content/drive/MyDrive/customer-intelligence-pipeline'
raw_data_path = os.path.join(project_path, 'data/raw')

Mounted at /content/drive

In [2]:
# Load the data
customers = pd.read_csv(os.path.join(raw_data_path, 'customers.csv'))
orders = pd.read_csv(os.path.join(raw_data_path, 'orders.csv'))

In [3]:
#information of Dataset

print(customers.info())
print(orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   object
 1   signup_date       1000 non-null   object
 2   segment           1000 non-null   object
 3   region            1000 non-null   object
 4   email_subscribed  1000 non-null   bool
dtypes: bool(1), object(4)
memory usage: 32.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     5000 non-null   object
 1   customer_id  5000 non-null   object
 2   order_date   5000 non-null   object
 3   amount       5000 non-null   float64
 4   status       5000 non-null   object
dtypes: float64(1), object(4)
memory usage: 195.4+ KB
None

In [4]:
#Converting Dates

orders['order_date']=pd.to_datetime(orders['order_date'])
customers['signup_date']=pd.to_datetime(customers['signup_date'])

In [5]:
print(orders['order_date'].dtypes)
print(customers['signup_date'].dtypes)

datetime64[ns]
datetime64[ns]

In [6]:
#rows and columns in orders table
print(f'the rows of orders table are {orders.shape[0]}')
print(f'the columns of orders table are {orders.shape[1]}')

#rows and columns in customers table
print(f'the rows of customers table are {customers.shape[0]} ')
print(f'the columns of custtomers table are {customers.shape[1]}')

the rows of orders table are 5000
the columns of orders table are 5
the rows of customers table are 1000
the columns of custtomers table are 5

## Customer Data Exploration

In [7]:
print("\n1. First few rows:")
print(customers.head())

1. First few rows:
  customer_id                signup_date     segment         region  \
0  CUST_00001 2025-09-13 15:49:50.749659    Standard           Asia
1  CUST_00002 2024-03-22 15:49:50.749659  Enterprise  South America
2  CUST_00003 2023-12-24 15:49:50.749659     Premium         Europe
3  CUST_00004 2024-09-05 15:49:50.749659    Standard  South America
4  CUST_00005 2024-08-05 15:49:50.749659    Standard  South America

   email_subscribed
0              True
1              True
2              True
3              True
4              True

In [8]:
print("\n2️. Data types and missing values:")
print(customers.info())

2️. Data types and missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   object
 1   signup_date       1000 non-null   datetime64[ns]
 2   segment           1000 non-null   object
 3   region            1000 non-null   object
 4   email_subscribed  1000 non-null   bool
dtypes: bool(1), datetime64[ns](1), object(3)
memory usage: 32.4+ KB
None

In [9]:
customers.isnull().sum()

customer_id         0
signup_date         0
segment             0
region              0
email_subscribed    0
dtype: int64

In [10]:
print("\n3. Statistical summary:")
print(customers.describe())

3. Statistical summary:
                         signup_date
count                           1000
mean   2024-11-30 04:25:50.749658880
min       2023-11-29 15:49:50.749659
25%    2024-06-10 15:49:50.749658880
50%    2024-11-23 03:49:50.749658880
75%    2025-06-03 21:49:50.749658880
max       2025-11-28 15:49:50.749659

In [11]:
print("\n4️. Segment distribution:")
print(customers['segment'].value_counts())
print(f"\nSegment %:")
print((customers['segment'].value_counts() / len(customers) * 100).round(1))

4️. Segment distribution:
segment
Standard      613
Premium       287
Enterprise    100
Name: count, dtype: int64

Segment %:
segment
Standard      61.3
Premium       28.7
Enterprise    10.0
Name: count, dtype: float64

In [12]:
print("\n5️. Region distribution:")
print(customers['region'].value_counts())

5️. Region distribution:
region
North America    261
Europe           258
South America    241
Asia             240
Name: count, dtype: int64

In [13]:
print("\n6️. Email subscription rate:")
email_rate = customers['email_subscribed'].mean() * 100
print(f"   {email_rate:.1f}% subscribed to email")

6️. Email subscription rate:
   71.1% subscribed to email

In [14]:
print("\n7️. Signup date range:")
print(f"   Earliest: {customers['signup_date'].min().date()}")
print(f"   Latest: {customers['signup_date'].max().date()}")
print(f"   Span: {(customers['signup_date'].max() - customers['signup_date'].min()).days} days")

7️. Signup date range:
   Earliest: 2023-11-29
   Latest: 2025-11-28
   Span: 730 days

## Order Data Exploration

In [15]:

print('\n1. First few rows:')
print(orders.head())

1. First few rows:
     order_id customer_id                 order_date  amount     status
0  ORD_000001  CUST_00103 2025-10-15 15:49:50.749659  115.86  Completed
1  ORD_000002  CUST_00021 2024-04-18 15:49:50.749659  336.30  Completed
2  ORD_000003  CUST_00467 2025-02-04 15:49:50.749659  182.72  Completed
3  ORD_000004  CUST_00872 2025-08-26 15:49:50.749659   79.34  Completed
4  ORD_000005  CUST_00662 2025-11-15 15:49:50.749659  217.55   Returned

In [16]:
print('\n2. Data  types and missing values:')
print(orders.info())

2. Data  types and missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     5000 non-null   object
 1   customer_id  5000 non-null   object
 2   order_date   5000 non-null   datetime64[ns]
 3   amount       5000 non-null   float64
 4   status       5000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 195.4+ KB
None

In [17]:
orders.isnull().sum()

order_id       0
customer_id    0
order_date     0
amount         0
status         0
dtype: int64

In [18]:
print('\n3. Order Amount Statistics:')
print(orders['amount'].describe())

3. Order Amount Statistics:
count    5000.000000
mean      341.627398
std       446.960959
min         6.200000
25%       102.122500
50%       203.810000
75%       411.947500
max      9464.630000
Name: amount, dtype: float64

In [19]:
print("\n4️. Order status distribution:")
print(orders['status'].value_counts())
print(f"\nStatus %:")
print((orders['status'].value_counts()/len(orders)*100),round(1))

4️. Order status distribution:
status
Completed    4519
Returned      248
Cancelled     233
Name: count, dtype: int64

Status %:
status
Completed    90.38
Returned      4.96
Cancelled     4.66
Name: count, dtype: float64 1

In [20]:
print('\n Order data Range')
print(f'Earliest:{orders['order_date'].min().date()}')
print(f'Latest:{orders['order_date'].max().date()}')

 Order data Range
Earliest:2023-12-13
Latest:2025-11-29

In [21]:
print('\n6. Revenue Metrics:')
total_revenue=orders[orders['status'] =='Completed']['amount'].sum().round(1)
print(f'   Total revenue is {total_revenue}')
print(f"   Average order value: ${orders['amount'].mean():,.2f}")
print(f"   Median order value: ${orders['amount'].median():,.2f}")
print(f"   Min order: ${orders['amount'].min():,.2f}")
print(f"   Max order: ${orders['amount'].max():,.2f}")

6. Revenue Metrics:
   Total revenue is 1544753.8
   Average order value: $341.63
   Median order value: $203.81
   Min order: $6.20
   Max order: $9,464.63

In [22]:
print('\n6. Customer Behaviour')
customers_with_orders=orders['customer_id'].nunique()
print(f"   Total unique customers who ordered: {customers_with_orders}")
print(f"   % of all customers: {(customers_with_orders/len(customers)*100):.1f}%")

6. Customer Behaviour
   Total unique customers who ordered: 988
   % of all customers: 98.8%

## Data Quality Check

In [23]:
print('\n1. Missing Values' )
print(f' Customers missing values {customers.isnull().sum()}')
print(f' Orders missing values {orders.isnull().sum()}')

1. Missing Values
 Customers missing values customer_id         0
signup_date         0
segment             0
region              0
email_subscribed    0
dtype: int64
 Orders missing values order_id       0
customer_id    0
order_date     0
amount         0
status         0
dtype: int64

In [24]:
print('\n2. Duplicates value')
print(f' Customers Duplicate values {customers.duplicated().sum()}')
print(f' Orders Duplicate values {orders.duplicated().sum()}')

2. Duplicates value
 Customers Duplicate values 0
 Orders Duplicate values 0

In [25]:
print('\n3. Data Integrity Check')
order_customers= set(orders['customer_id'].unique())
valid_customers= set(customers['customer_id'].unique())
orphan_orders = order_customers - valid_customers

if len(orphan_orders)>0:
  print(f"{len(orphan_orders)} orders reference non-existent customers")
else:
    print(f" All {len(order_customers)} customers in orders exist in customer data")

3. Data Integrity Check
 All 988 customers in orders exist in customer data

In [26]:
print('\n4, Order Amount Validation')
if (orders['amount']>0).all():
  print('All amounts are positive')
else:
  print(f'{(orders["amount"]<=0).sum()} orders have zero/neagtive value')

4, Order Amount Validation
All amounts are positive

Key Metrics

In [27]:
print('\n1. Customer level Metric' )
customer_metric=orders.groupby('customer_id').agg({'order_id':'count',
                                                   'amount':['sum','mean'],
                                                   'order_date':'max'}).reset_index()

customer_metric.columns=['customer_id', 'num_orders', 'total_spent', 'avg_order_value', 'last_order_date']

1. Customer level Metric

In [28]:
customer_metric

,customer_id,num_orders,total_spent,avg_order_value,last_order_date
0,CUST_00001,7,1880.39,268.627143,2025-11-09 15:49:50.749659
1,CUST_00002,6,2192.10,365.350000,2025-02-06 15:49:50.749659
2,CUST_00003,4,1574.69,393.672500,2025-11-24 15:49:50.749659
3,CUST_00004,4,1269.52,317.380000,2025-10-13 15:49:50.749659
4,CUST_00005,6,2011.33,335.221667,2025-10-31 15:49:50.749659
...,...,...,...,...,...
983,CUST_00996,4,900.19,225.047500,2025-06-08 15:49:50.749659
984,CUST_00997,2,322.13,161.065000,2025-11-23 15:49:50.749659
985,CUST_00998,5,445.53,89.106000,2025-10-26 15:49:50.749659
986,CUST_00999,4,1062.31,265.577500,2025-11-10 15:49:50.749659
987,CUST_01000,6,2403.44,400.573333,2025-11-02 15:49:50.749659

In [29]:
# Calculate days since last order (recency)

today=orders['order_date'].max()
customer_metric['days_since_last_order']=(today-customer_metric['last_order_date']).dt.days
customer_metric

,customer_id,num_orders,total_spent,avg_order_value,last_order_date,days_since_last_order
0,CUST_00001,7,1880.39,268.627143,2025-11-09 15:49:50.749659,20
1,CUST_00002,6,2192.10,365.350000,2025-02-06 15:49:50.749659,296
2,CUST_00003,4,1574.69,393.672500,2025-11-24 15:49:50.749659,5
3,CUST_00004,4,1269.52,317.380000,2025-10-13 15:49:50.749659,47
4,CUST_00005,6,2011.33,335.221667,2025-10-31 15:49:50.749659,29
...,...,...,...,...,...,...
983,CUST_00996,4,900.19,225.047500,2025-06-08 15:49:50.749659,174
984,CUST_00997,2,322.13,161.065000,2025-11-23 15:49:50.749659,6
985,CUST_00998,5,445.53,89.106000,2025-10-26 15:49:50.749659,34
986,CUST_00999,4,1062.31,265.577500,2025-11-10 15:49:50.749659,19
987,CUST_01000,6,2403.44,400.573333,2025-11-02 15:49:50.749659,27

In [30]:
print("\n1. Customer purchase behavior:")
print(f"   Average # of orders per customer: {customer_metric['num_orders'].mean():.1f}")
print(f"   Average total spent per customer: ${customer_metric['total_spent'].mean():,.2f}")
print(f"   Max orders by single customer: {customer_metric['num_orders'].max()}")
print(f"   Max spent by single customer: ${customer_metric['total_spent'].max():,.2f}")

1. Customer purchase behavior:
   Average # of orders per customer: 5.1
   Average total spent per customer: $1,728.88
   Max orders by single customer: 13
   Max spent by single customer: $11,193.57

In [31]:
print("\n2️. Purchase recency (days since last order):")
print(f"   Average: {customer_metric['days_since_last_order'].mean():.1f} days")
print(f"   Median: {customer_metric['days_since_last_order'].median():.1f} days")
print(f"   Min (most recent): {customer_metric['days_since_last_order'].min()} days")
print(f"   Max (most inactive): {customer_metric['days_since_last_order'].max()} days")

2️. Purchase recency (days since last order):
   Average: 70.3 days
   Median: 39.0 days
   Min (most recent): 0 days
   Max (most inactive): 627 days

In [32]:
print("\n3️. Preview of customer metrics:")
print(customer_metric.head(10))

3️. Preview of customer metrics:
  customer_id  num_orders  total_spent  avg_order_value  \
0  CUST_00001           7      1880.39       268.627143
1  CUST_00002           6      2192.10       365.350000
2  CUST_00003           4      1574.69       393.672500
3  CUST_00004           4      1269.52       317.380000
4  CUST_00005           6      2011.33       335.221667
5  CUST_00006           5      2329.33       465.866000
6  CUST_00007           5      1535.69       307.138000
7  CUST_00008           3       638.01       212.670000
8  CUST_00009           3       433.00       144.333333
9  CUST_00010           6      1593.79       265.631667

             last_order_date  days_since_last_order
0 2025-11-09 15:49:50.749659                     20
1 2025-02-06 15:49:50.749659                    296
2 2025-11-24 15:49:50.749659                      5
3 2025-10-13 15:49:50.749659                     47
4 2025-10-31 15:49:50.749659                     29
5 2025-07-21 15:49:50.749659                    131
6 2025-08-07 15:49:50.749659                    114
7 2025-10-03 15:49:50.749659                     57
8 2025-11-15 15:49:50.749659                     14
9 2025-11-20 15:49:50.749659                      9

In [34]:
print('\n4. Segment Analysis')
#Merge with customer_segments
customer_metric_with_segment= customer_metric.merge(customers[['customer_id', 'segment', 'region']], on='customer_id')
customer_metric_with_segment

4. Segment Analysis

,customer_id,num_orders,total_spent,avg_order_value,last_order_date,days_since_last_order,segment,region
0,CUST_00001,7,1880.39,268.627143,2025-11-09 15:49:50.749659,20,Standard,Asia
1,CUST_00002,6,2192.10,365.350000,2025-02-06 15:49:50.749659,296,Enterprise,South America
2,CUST_00003,4,1574.69,393.672500,2025-11-24 15:49:50.749659,5,Premium,Europe
3,CUST_00004,4,1269.52,317.380000,2025-10-13 15:49:50.749659,47,Standard,South America
4,CUST_00005,6,2011.33,335.221667,2025-10-31 15:49:50.749659,29,Standard,South America
...,...,...,...,...,...,...,...,...
983,CUST_00996,4,900.19,225.047500,2025-06-08 15:49:50.749659,174,Standard,North America
984,CUST_00997,2,322.13,161.065000,2025-11-23 15:49:50.749659,6,Enterprise,Asia
985,CUST_00998,5,445.53,89.106000,2025-10-26 15:49:50.749659,34,Standard,North America
986,CUST_00999,4,1062.31,265.577500,2025-11-10 15:49:50.749659,19,Enterprise,Europe
987,CUST_01000,6,2403.44,400.573333,2025-11-02 15:49:50.749659,27,Standard,South America

In [37]:
segment_summary=customer_metric_with_segment.groupby('segment').agg({'num_orders':['sum','mean'],
                                                                     'total_spent':['count','mean','sum',],
                                                                     'days_since_last_order': 'mean'

                                                                     }).round(2)

In [40]:
print("\nAverage metrics by segment:")
print(f"{'Segment':<15} {'Count':<10} {'Avg Spent':<15} {'Total $':<15} {'Avg Orders':<12} {'Days Inactive':<12}")
print("-" * 80)
for segment in ['Standard', 'Premium', 'Enterprise']:
    data = customer_metric_with_segment[customer_metric_with_segment['segment'] == segment]
    print(f"{segment:<15} {len(data):<10} ${data['total_spent'].mean():<14,.0f} ${data['total_spent'].sum():<14,.0f} {data['num_orders'].mean():<12.1f} {data['days_since_last_order'].mean():<12.1f}")

Average metrics by segment:
Segment         Count      Avg Spent       Total $         Avg Orders   Days Inactive
--------------------------------------------------------------------------------
Standard        603        $1,772          $1,068,622      5.2          70.1
Premium         287        $1,685          $483,723        4.9          68.8
Enterprise      98         $1,590          $155,793        4.9          76.5

## Customer Churn Analysis

In [48]:
# Defining churn risk based on recency
# If no order in last 60 days = HIGH RISK

customer_metric['churn risk']=customer_metric['days_since_last_order']>=60

print(f"\n1️. At-risk customers (no order in 60+ days):")
at_risk_count=customer_metric['churn risk'].sum()
print(f"   Count: {at_risk_count} customers")
print(f"   % of customers: {(at_risk_count/len(customer_metric)*100):.1f}%")

1️. At-risk customers (no order in 60+ days):
   Count: 376 customers
   % of customers: 38.1%

In [51]:
print(f"\n2️. Risk distribution:")
print(f"   Active (0-30 days): {(customer_metric['days_since_last_order'] < 30).sum()}")
print(f"   Moderate (30-60 days): {((customer_metric['days_since_last_order'] >= 30) & (customer_metric['days_since_last_order'] < 60)).sum()}")
print(f"   At Risk (60+ days): {(customer_metric['days_since_last_order'] >= 60).sum()}")

2️. Risk distribution:
   Active (0-30 days): 415
   Moderate (30-60 days): 197
   At Risk (60+ days): 376

In [53]:
print(f"\n3️. At-risk customers by segment:")
at_risk_by_segment = customer_metric_with_segment.copy()
at_risk_by_segment['churn_risk'] = at_risk_by_segment['days_since_last_order'] >= 60


for segment in ['Standard', 'Premium', 'Enterprise']:
    segment_data = at_risk_by_segment[at_risk_by_segment['segment'] == segment]
    at_risk = segment_data['churn_risk'].sum()
    total = len(segment_data)
    print(f"   {segment}: {at_risk}/{total} at risk ({(at_risk/total*100):.1f}%)")

3️. At-risk customers by segment:
   Standard: 235/603 at risk (39.0%)
   Premium: 100/287 at risk (34.8%)
   Enterprise: 41/98 at risk (41.8%)

In [56]:
print(f"\n4️.  Top 10 at-risk customers (no orders in 60+ days):")

at_risk_customers = customer_metric_with_segment[customer_metric_with_segment['days_since_last_order'] >= 60].sort_values('days_since_last_order', ascending=False).head(10)
print(at_risk_customers[['customer_id', 'segment', 'total_spent', 'num_orders', 'days_since_last_order']])

4️.  Top 10 at-risk customers (no orders in 60+ days):
    customer_id     segment  total_spent  num_orders  days_since_last_order
441  CUST_00448     Premium       176.44           1                    627
43   CUST_00044  Enterprise      1109.21           2                    458
31   CUST_00032    Standard       483.15           2                    453
889  CUST_00901    Standard       696.26           4                    442
93   CUST_00094    Standard       243.13           1                    436
541  CUST_00548     Premium      1297.38           2                    418
462  CUST_00469    Standard       686.72           2                    397
578  CUST_00585     Premium       395.14           2                    393
447  CUST_00454  Enterprise       487.95           2                    393
229  CUST_00232    Standard      1379.07           2                    385